### ISSUE TITLE
FMDBTransformerForKey

### ISSUE THREAD

**Issue by wuchuwuyou** [tanis2000/MTLFMDBAdapter#10]
method: - (NSValueTransformer *)FMDBTransformerForKey:(NSString *)key;
changed ==>  + (NSValueTransformer *)FMDBTransformerForKey:(NSString *)key;
can be work ? This is a error  or ??

**Comment by tanis2000** [comment]
Indeed that was a typo. It should have been corrected since then. Please let me know if you spot anything similar. Cheers!
