### ISSUE TITLE
Error on Pod Install

### ISSUE THREAD

**Issue by engmsaleh** [tanis2000/MTLFMDBAdapter#14]
When I'm trying to install it using Pod I get the following error
```
[!] Unable to satisfy the following requirements:

- `Mantle (~> 2.0)` required by `Podfile`
- `Mantle (= 2.0)` required by `Podfile.lock`
- `Mantle (~> 1.5)` required by `MTLFMDBAdapter (0.1.0)`
```

**Comment by tanis2000** [comment]
You've got a dependency on a more recent release of Mantle (2.0) while we still use 1.5
There are some incompatible changes between the two releases so we haven't yet migrated to the 2.x branch. If you're not using any of the 2.0 features of Mantle you might as well just replace `pod 'Mantle', '~> 2.0'` with `pod 'Mantle', '~> 1.5'` in your Podfile

**Comment by engmsaleh** [comment]
Hi @tanis2000  Thanks for clarifications, but unfortunately I already have downgraded the Mantle version and I found that I'm indeed using functionality from Mantle 2.0 , so I will have to stay on Mantle 2.0. 
Could you advise if there are any similar ways to interact with FMDB in my current Mantle version?

**Comment by tanis2000** [comment]
I've just pushed an update to CocoaPods. Try switching to v0.2.0 of MTLFMDBAdapter and let me know if that solves your problems.

**Comment by engmsaleh** [comment]
Thanks a lot @tanis2000 , I have installed it using pod successfully ;) , thanks a lot for your awesome work.

**Comment by tanis2000** [comment]
That's good to hear! I'm closing this issue :)
