### ISSUE TITLE
Nill value crash

### ISSUE THREAD

**Issue by akovalovrw** [tanis2000/MTLFMDBAdapter#16]
Hi, there is some cases when code causes crash. I'm not sure why exactly it happens because only on users devices. Attached screenshot from Fabric for your reference. 

<img width="971" alt="screen shot 2016-03-22 at 7 01 19 pm" src="https://cloud.githubusercontent.com/assets/16556858/13960350/a68bb058-f060-11e5-8b78-5cb148d54e55.png">

Also I see that in the following code that there is no checking for nil value while adding in array.
`if (keyPath != nil && ![keyPath isEqual:[NSNull null]])
        {
            [values addObject:[dictionaryValue valueForKey:propertyKey]];
        }
`

Could you check that please? Let me know If I can help more. 
Thank you.

**Comment by tanis2000** [comment]
It looks like there's a missing entry in the `dictionaryValue`. I'll have a look at it either later tonight or tomorrow and add a safe-belt check there to spot the error in the code. 
I'll keep you updated.

**Comment by tanis2000** [comment]
This should fix your issue: https://github.com/tanis2000/MTLFMDBAdapter/commit/63f2a18d4dab05c1315ec1f9cbb7e9dae09d2078

If it works for you I'll bring it upstream.

**Comment by akovalovrw** [comment]
Thank you for the fast fix! 
It definitely fixes crash due to adding nil value into array.

**Comment by tanis2000** [comment]
Updated Cocoapods as well. I'm closing this. Feel free to reopen if needed.

**Comment by akovalovrw** [comment]
I've looked dipper into my code today. And probably this issue was due to my specific code with querying FMDB from different threads. I had to rewrite some to thread safety and probably nil value crash in MTLFMDBAdapter will not happen again. But, please, look into comments I've posted to referenced commit. Thank you.

**Comment by tanis2000** [comment]
The latest changes shouldn't affect your code, but I'll have another look at it as soon as I'm back home next week. You might want to come up with a few tests to demonstrate what's wrong. That would definitely help.

Regards.

Valerio Santinelli

Inviato da iPhone
