### ISSUE TITLE
[MTLFMDBAdapter columnValues] does not honor value transformers.

### ISSUE THREAD

**Issue by ptwohig** [tanis2000/MTLFMDBAdapter#17]
A quick inspection of the code and my unit tests reveal that it simply does not FMDBTransformerForKey for each key in the model.  This is of little use unless the conversion can be made bidirectional.

**Comment by tanis2000** [comment]
Can you share the tests? I'll have a look at this.

**Comment by ptwohig** [comment]
I just lifted your method from the MTLFMDBAdapter and added it to my code.

`+ (NSArray *)columnValues:(MTLModel<MTLFMDBSerializing> *)model {
    NSDictionary *columns = [model.class FMDBColumnsByPropertyKey];
    NSSet *propertyKeys = [model.class propertyKeys];
    NSArray *Keys = [[propertyKeys allObjects] sortedArrayUsingSelector:@selector(compare:)];
    NSDictionary *dictionaryValue = model.dictionaryValue;
    NSMutableArray *values = [NSMutableArray array];
    for (NSString *propertyKey in Keys)
    {
        NSString *keyPath = columns[propertyKey];
        keyPath = keyPath ? : propertyKey;
        
        if (keyPath != nil && ![keyPath isEqual:[NSNull null]])
        {
            id v = [dictionaryValue valueForKey:propertyKey];
            NSValueTransformer * transformer = [self valueTransformerForModel:model propertyKey:propertyKey];
            
            if (transformer) {
                v = [transformer reverseTransformedValue:v];
            }

            if (v == nil) {
                NSLog(@"Warning: value for key %@ is nil", propertyKey);
                v = [NSNull null];
            }

            [values addObject:v];

        }
    }
    return values;
}

+(NSValueTransformer*) valueTransformerForModel:(MTLModel<MTLFMDBSerializing>*)model propertyKey:(NSString*)key {

    Class cls = [model class];

    SEL selector = MTLSelectorWithKeyPattern(key, "FMDBTransformer");

    if ([cls respondsToSelector:selector]) {
        NSInvocation *invocation = [NSInvocation invocationWithMethodSignature:[cls methodSignatureForSelector:selector]];
        invocation.target = cls;
        invocation.selector = selector;
        [invocation invoke];
        
        __unsafe_unretained id result = nil;
        [invocation getReturnValue:&result];
        return result;
    }
    
    if ([cls respondsToSelector:@selector(FMDBTransformerForKey:)]) {
        return [cls FMDBTransformerForKey:key];
    }
    
    return nil;
}
`

**Comment by ptwohig** [comment]
I hope this illustrates the problem.  It should be a simple fix, can also make  PR if you want.

**Comment by tanis2000** [comment]
If you can submit a PR that would be awesome and would make things even quicker

**Comment by tanis2000** [comment]
This has been solved in version 0.3.2
