### ISSUE TITLE
"FMDBTransformer" value transformer don't declare in MTLFMDBSerializing?

### ISSUE THREAD

**Issue by todaylover** [tanis2000/MTLFMDBAdapter#7]
I think the declare shoud be there

**Comment by tanis2000** [comment]
Sorry but I don't understand what you mean..

**Comment by todaylover** [comment]
"FMDBTransformerForKey:" method has not't be declared in "MTLFMDBSerializing" protocol, then others could't known they can use transformer to transform the value fetched from FMDB when they just see the header file.
